name: 'cookalchemy-dev'

services:
  database:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/.dbs/postgres/ca:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/ca.sql
    environment:
      - POSTGRES_PASSWORD=sekret
      - POSTGRES_USER=su
      - POSTGRES_DB=ca
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "outside:host-gateway"
