name: 'cookalchemy-dev'

services:
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/.dbs/postgres/ca:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/ca.sql
    environment:
      - POSTGRES_PASSWORD=sekret
      - POSTGRES_USER=su
      - POSTGRES_DB=ca